In [12]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape # 查看张量的形状（维度大小）
# 因为x是一维的，有12个元素，所以shape是 torch.Size([12])

torch.Size([12])

In [8]:
x.numel() #元素的种数or返回张量中元素的总个数（与shape中各维度乘积相同）

12

In [13]:
x.reshape(3,4)  # 输出一个形状为(3,4)的二维张量

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
torch.zeros((2,3,4)) #深度2 长3 宽4 的三维张量

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
torch.tensor([[2,1,4,3],
              [4,5,6,7],
              [8,9,10,11]])
# 使用嵌套列表直接创建张量

tensor([[ 2,  1,  4,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [19]:
torch.tensor([[[2,1,4,3],
              [4,5,6,7],
              [8,9,10,11]]]).shape
# 理解：这是一个1张3×4的矩阵的三维张量。相当于在一个深度（batch/depth）为1的容器里放了一张3行4列的表格。

torch.Size([1, 3, 4])

In [27]:
# 创建浮点型张量（因为第一个元素是1.0，会自动转为float32）
x = torch.tensor([1.0,2,4,8])
# 创建整型张量（默认int64）
y = torch.tensor([2,2,2,2])
print(x + y)
print(x - y)
print(x * y)  # 逐元素乘法（哈达玛积，非矩阵乘法）
print(x / y)  # 逐元素真除法（结果总是浮点数，即使两个整数相除）
print(x % y)  # 逐元素取模（余数）,结果符号与除数相同
print(x ** y) # 逐元素幂运算：x 的 y 次方

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([1., 0., 0., 0.])
tensor([ 1.,  4., 16., 64.])
