In [12]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape # 查看张量的形状（维度大小）
# 因为x是一维的，有12个元素，所以shape是 torch.Size([12])

torch.Size([12])

In [8]:
x.numel() #元素的种数or返回张量中元素的总个数（与shape中各维度乘积相同）

12

In [13]:
x.reshape(3,4)  # 输出一个形状为(3,4)的二维张量

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
torch.zeros((2,3,4)) #深度2 长3 宽4 的三维张量

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])