In [2]:
import torch
from pandas.core.arrays.arrow import dtype

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape # 查看张量的形状（维度大小）
# 因为x是一维的，有12个元素，所以shape是 torch.Size([12])

torch.Size([12])

In [4]:
x.numel() #元素的种数or返回张量中元素的总个数（与shape中各维度乘积相同）

12

In [5]:
x.reshape(3,4)  # 输出一个形状为(3,4)的二维张量

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4)) #深度2 长3 宽4 的三维张量

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.tensor([[2,1,4,3],
              [4,5,6,7],
              [8,9,10,11]])
# 使用嵌套列表直接创建张量

tensor([[ 2,  1,  4,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.tensor([[[2,1,4,3],
              [4,5,6,7],
              [8,9,10,11]]]).shape
# 理解：这是一个1张3×4的矩阵的三维张量。相当于在一个深度（batch/depth）为1的容器里放了一张3行4列的表格。

torch.Size([1, 3, 4])

In [10]:
# 创建浮点型张量（因为第一个元素是1.0，会自动转为float32）
x = torch.tensor([1.0,2,4,8])
# 创建整型张量（默认int64）
y = torch.tensor([2,2,2,2])
print(x + y)
print(x - y)
print(x * y)  # 逐元素乘法（哈达玛积，非矩阵乘法）
print(x / y)  # 逐元素真除法（结果总是浮点数，即使两个整数相除）
print(x % y)  # 逐元素取模（余数）,结果符号与除数相同
print(x ** y) # 逐元素幂运算：x 的 y 次方
# 结果带小数点是因为 运算结果的张量是浮点类型

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([1., 0., 0., 0.])
tensor([ 1.,  4., 16., 64.])


In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [30]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
# 外层括号：是函数 reshape() 的调用括号，必不可少。
# 内层括号：是 元组 (3,4) 的括号，因为 reshape 需要一个表示形状的参数，这里我们传入一个元组 (3,4) 作为参数。
Y = torch.tensor(([2.0,1,4,3],
                  [4,5,6,7],
                  [8,9,10,11]))
torch.cat((X,Y),dim = 0), torch.cat((X,Y),dim = 1)
# 输出带(是因为用了逗号把两个torch.cat的结果连在了一起,形成一个元组（tuple）

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]]))

In [31]:
X == Y

tensor([[False,  True, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [32]:
X.sum()

tensor(66.)

In [36]:
# 广播机制：当两个张量形状不同时，PyTorch 会自动尝试通过“扩展”某些维度，使它们形状兼容，从而执行逐元素运算（如加法、乘法等）。这个过程不需要复制数据，内存高效。
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [38]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 数据读取

In [39]:
X[-1] # 访问X的最后一行
#规范书写：X[-1,:]

tensor([ 8.,  9., 10., 11.])

In [40]:
X[1:3]
#规范书写：X[1：3,:]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### 数据写入

In [41]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])